
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Osman
 */
public class FlightSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form FlightSchedulerGUI
     */
    public FlightSchedulerGUI() {
        initComponents();
        int pos;
        BookingNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getAllPassengers().toArray()));
        BookingFNamCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        BookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        WaitListCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        FlightDayNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        FlightDayDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        StatusCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getAllPassengers().toArray()));
        CancelDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        CancelNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getAllPassengers().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        PAss = new javax.swing.JTabbedPane();
        ADDPASSENGERPANEL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        WAITLISTPANEL = new javax.swing.JPanel();
        WaitListCombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();
        jLabel7 = new javax.swing.JLabel();
        BOOKINGPANEL = new javax.swing.JPanel();
        BookingNameCombo = new javax.swing.JComboBox<>();
        BookingFNamCombo = new javax.swing.JComboBox<>();
        AddBookingButton = new javax.swing.JButton();
        BookingDateCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BookingStatusLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightDayTextArea = new javax.swing.JTextArea();
        FlightDayStatusButton = new javax.swing.JButton();
        FlightDayDateCombo = new javax.swing.JComboBox<>();
        FlightDayNameCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AddFlightButton = new javax.swing.JButton();
        AddFlightNameTF = new javax.swing.JTextField();
        AddFlightSeatsTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        StatusCustomerCombo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        CancelNameCombo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        CancelDateCombo = new javax.swing.JComboBox<>();
        CancelButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        DropFlightCombo = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PAss.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PAssStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("NAME:");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("ADD TO PASSENGERS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("ENTER PASSENGER NAME");

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("STATUS: ");

        javax.swing.GroupLayout ADDPASSENGERPANELLayout = new javax.swing.GroupLayout(ADDPASSENGERPANEL);
        ADDPASSENGERPANEL.setLayout(ADDPASSENGERPANELLayout);
        ADDPASSENGERPANELLayout.setHorizontalGroup(
            ADDPASSENGERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDPASSENGERPANELLayout.createSequentialGroup()
                .addGroup(ADDPASSENGERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ADDPASSENGERPANELLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(ADDPASSENGERPANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(73, 73, 73)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        ADDPASSENGERPANELLayout.setVerticalGroup(
            ADDPASSENGERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDPASSENGERPANELLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(ADDPASSENGERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(ADDPASSENGERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        PAss.addTab("ADD PASSENGER", ADDPASSENGERPANEL);

        WaitListCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        WaitListCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitListComboActionPerformed(evt);
            }
        });

        jButton2.setText("GET WAITLIST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("CHOOSE DATE: ");

        javax.swing.GroupLayout WAITLISTPANELLayout = new javax.swing.GroupLayout(WAITLISTPANEL);
        WAITLISTPANEL.setLayout(WAITLISTPANELLayout);
        WAITLISTPANELLayout.setHorizontalGroup(
            WAITLISTPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WAITLISTPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaitListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton2)
                .addContainerGap(499, Short.MAX_VALUE))
            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WAITLISTPANELLayout.setVerticalGroup(
            WAITLISTPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WAITLISTPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WAITLISTPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(WaitListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PAss.addTab("STATUS:WAITLIST", WAITLISTPANEL);

        BOOKINGPANEL.setForeground(new java.awt.Color(255, 255, 255));

        BookingNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BookingNameCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BookingNameComboFocusGained(evt);
            }
        });
        BookingNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingNameComboActionPerformed(evt);
            }
        });

        BookingFNamCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BookingFNamCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingFNamComboActionPerformed(evt);
            }
        });

        AddBookingButton.setText("ADD BOOKING");
        AddBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookingButtonActionPerformed(evt);
            }
        });

        BookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BookingDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingDateComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("NAME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("FLIGHT NUMBER:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("DATE:");

        BookingStatusLabel.setForeground(new java.awt.Color(255, 51, 51));
        BookingStatusLabel.setText("CHOOSE FLIGHT TO BOOK");

        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("STATUS: ");

        javax.swing.GroupLayout BOOKINGPANELLayout = new javax.swing.GroupLayout(BOOKINGPANEL);
        BOOKINGPANEL.setLayout(BOOKINGPANELLayout);
        BOOKINGPANELLayout.setHorizontalGroup(
            BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(45, 45, 45)
                                    .addComponent(BookingDateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(45, 45, 45)
                                    .addComponent(BookingNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                                .addComponent(AddBookingButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookingStatusLabel))))
                    .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BookingFNamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        BOOKINGPANELLayout.setVerticalGroup(
            BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKINGPANELLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(BookingFNamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BookingDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(BOOKINGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBookingButton)
                    .addComponent(BookingStatusLabel)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        PAss.addTab("ADD BOOKING ", BOOKINGPANEL);

        FlightDayTextArea.setColumns(20);
        FlightDayTextArea.setRows(5);
        jScrollPane2.setViewportView(FlightDayTextArea);

        FlightDayStatusButton.setText("CHECK STATUS");
        FlightDayStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightDayStatusButtonActionPerformed(evt);
            }
        });

        FlightDayDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FlightDayDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightDayDateComboActionPerformed(evt);
            }
        });

        FlightDayNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FlightDayNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightDayNameComboActionPerformed(evt);
            }
        });

        jLabel1.setText("FLIGHTNAME:");

        jLabel9.setText("DATE:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setText("PASSENGER NAMES:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FlightDayNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlightDayDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(FlightDayStatusButton)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightDayStatusButton)
                    .addComponent(FlightDayDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightDayNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PAss.addTab("STATUS:FLIGHT DAY", jPanel1);

        jLabel12.setText("FLIGHT NAME: ");

        AddFlightButton.setText("ADD FLIGHT");
        AddFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightButtonActionPerformed(evt);
            }
        });

        AddFlightNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AddFlightNameTFFocusGained(evt);
            }
        });
        AddFlightNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightNameTFActionPerformed(evt);
            }
        });

        jLabel14.setText("SEATS:");

        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("STATUS:");

        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("ENTER FLIGHT NAME AND SEATS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddFlightSeatsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddFlightNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(AddFlightButton)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addGap(468, 468, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AddFlightNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AddFlightSeatsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFlightButton)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(61, 61, 61))
        );

        PAss.addTab("ADD FLIGHT", jPanel2);

        jLabel17.setText("DATE: ");

        jButton3.setText("ADD DATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("STATUS:");

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("ENTER DATE TO ADD");

        jLabel20.setText("FORMAT: YYYY-MM-DD ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addContainerGap(548, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(70, 70, 70))
        );

        PAss.addTab("ADD DATES", jPanel3);

        StatusCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StatusCustomerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusCustomerComboActionPerformed(evt);
            }
        });

        jLabel21.setText("NAME:");

        jButton6.setText("GET STATUS ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton6)
                .addContainerGap(553, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PAss.addTab("STATUS: CUSTOMER", jPanel4);

        jLabel22.setText("NAME:");

        CancelNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CancelNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelNameComboActionPerformed(evt);
            }
        });

        jLabel23.setText("DATE:");

        CancelDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setText("STATUS BOOKING:");

        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setText("CHOOSE PASSENGER AND DATE");

        jLabel31.setForeground(new java.awt.Color(255, 51, 51));
        jLabel31.setText("STATUS WAITLIST:");

        jLabel32.setForeground(new java.awt.Color(255, 0, 51));
        jLabel32.setText("CHOOSE PASSENGER AND DATE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(CancelNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(CancelDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(CancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel25))))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(CancelNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        PAss.addTab("CANCEL", jPanel6);

        jLabel26.setText("FLIGHT NUMBER:");

        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("DROP");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("STATUS:");

        jLabel28.setForeground(new java.awt.Color(255, 51, 51));
        jLabel28.setText("STATUS:");

        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("CHOOSE FLIGHT TO DROP");

        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("CHOOSE FLIGHT TO DROP");

        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("STATUS:");

        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("CHOOSE FLIGHT TO DROP");

        jLabel35.setForeground(new java.awt.Color(255, 0, 51));
        jLabel35.setText("STATUS:");

        jLabel36.setForeground(new java.awt.Color(255, 0, 51));
        jLabel36.setText("CHOOSE FLIGHT TO DROP");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel35)))
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel34)
                            .addComponent(jLabel36)))
                    .addComponent(jButton5))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(DropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(72, 72, 72))
        );

        PAss.addTab("DROP", jPanel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("FLIGHT SCEDUELER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PAss)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(PAss, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookingButtonActionPerformed

        String name = BookingNameCombo.getSelectedItem().toString();
        String flightName = BookingFNamCombo.getSelectedItem().toString();
        int result = 0;
        Date day = Date.valueOf(BookingDateCombo.getSelectedItem().toString());
        Waitlist wait = new Waitlist();
        Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        Booking booking = new Booking();
        Flight flight = new Flight();
        int x = booking.getSeatsBooked(flightName, day);
        int y = flight.getLeftSeats(flightName);
        if (x == y){
           result = wait.addWaitlist(name,flightName,day,timestamp);
           BookingStatusLabel.setText("Sorry! Mr/Ms: "+name+" flight: " +flightName+" is full but you are on the Wait List!");}
        else{
            result = booking.addBooking(name,flightName,day,timestamp);
            BookingStatusLabel.setText("Congratulations, Mr/Ms: "+name+" you have been booked for flight: "+flightName+" Departing on: "+day+" !");
        }
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_AddBookingButtonActionPerformed

    private void BookingFNamComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingFNamComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingFNamComboActionPerformed

    private void BookingNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingNameComboActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_BookingNameComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Passenger passenger = new Passenger();
        String str = jTextField1.getText();
        int result = passenger.addPassenger(str);
        if (result == 99){
        jLabel6.setText("Sorry "+"'"+str+"'"+" could not be added to list of passengers an error occured" ); 
        }
        else{
        jLabel6.setText("'"+str+"'"+" Successfully Added to list of Passengers!");
        BookingNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getAllPassengers().toArray()));
        StatusCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getAllPassengers().toArray()));
        CancelNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getAllPassengers().toArray()));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PAssStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PAssStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PAssStateChanged

    private void BookingDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingDateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingDateComboActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
    jLabel6.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void BookingNameComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BookingNameComboFocusGained
    BookingStatusLabel.setText("Choose Flight to book");        // TODO add your handling code here:
    }//GEN-LAST:event_BookingNameComboFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Waitlist wait = new Waitlist();
    Date day = Date.valueOf(WaitListCombo.getSelectedItem().toString());
    try{ 
    String ss ="";
    List result = wait.getCustomersBookedWaitlist(day);
    for(int i=0;i<result.size();i++){
    ss += result.get(i).toString();}
    
    textArea1.setText(ss);
    }catch(SQLException eq){
        
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void WaitListComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitListComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaitListComboActionPerformed

    private void FlightDayDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightDayDateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightDayDateComboActionPerformed

    private void FlightDayStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightDayStatusButtonActionPerformed
    Booking book = new Booking();
    Date day = Date.valueOf(FlightDayDateCombo.getSelectedItem().toString());
    String name = (FlightDayNameCombo.getSelectedItem().toString());
    try{
    String ss ="";
    List result = book.getCustomersBooked(name,day);
    for(int i=0;i<result.size();i++){
    ss += result.get(i).toString();}
    FlightDayTextArea.setText(ss);
    }
    
    catch(SQLException eq){
        eq.printStackTrace();
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_FlightDayStatusButtonActionPerformed

    private void FlightDayNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightDayNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightDayNameComboActionPerformed

    private void AddFlightNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFlightNameTFActionPerformed

    private void AddFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightButtonActionPerformed
    Flight flight = new Flight();
    int result;
    String name = AddFlightNameTF.getText();
    int seats = Integer.valueOf(AddFlightSeatsTF.getText());
    result = flight.addFlight(name, seats);
    if (result == 99){
        jLabel16.setText("Could not add Flight: "+ name+" as an error occured! Try again.");
        
    }else{
        jLabel16.setText("Fligth: "+name+" successfully added!");
        BookingFNamCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        FlightDayNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        
    }
    
    
    
    // TODO add your handling code here:
    }//GEN-LAST:event_AddFlightButtonActionPerformed

    private void AddFlightNameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddFlightNameTFFocusGained
    jLabel16.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_AddFlightNameTFFocusGained

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Day day = new Day();
    int result;
    String date = jTextField2.getText();
    result = day.addDay(Date.valueOf(date));
    if (result == 99){
        jLabel19.setText("Could not add Date: "+ date+" as an error occured! Try again.");
        
    }else{
        jLabel19.setText("Date: "+date+" successfully added!");
        BookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        FlightDayDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        WaitListCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        CancelDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDays().toArray()));
        
    }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
    jLabel19.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusGained

    private void StatusCustomerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusCustomerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusCustomerComboActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        Booking book = new Booking();
        Waitlist waitlist = new Waitlist();
        Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        
        int result;
        int result5;
        List result2;
        List result3;
       
        int result4;
        int result6;
        
        String name = CancelNameCombo.getSelectedItem().toString();
        String date = CancelDateCombo.getSelectedItem().toString(); 
        result3 = book.GetFlight(name, Date.valueOf(date));
        result = book.deleteBooking(name,Date.valueOf(date));// TODO add your handling code here:
        jLabel25.setText("Passenegr: "+"'"+name+"'"+" deleted from bookings for flight: "+result3.get(0).toString()+" departing: "+Date.valueOf(date));
        result5 = waitlist.getWaitListSize();
        if (result5 != 0){
            result2 = waitlist.shiftToBooking(result3.get(0).toString(),Date.valueOf(date));
            result4 = book.addBooking(result2.get(0).toString(),result3.get(0).toString(),Date.valueOf(date),timestamp);
            result6 = waitlist.deleteWaitlist(result2.get(0).toString());
            jLabel32.setText("'"+result2.get(0).toString()+"' "+" Booked for flight: "+result3.get(0).toString()+" departing: "+Date.valueOf(date));}
    
        else{
            jLabel32.setText("Wait list is Empty!");
        }
        
        
        
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Waitlist wait = new Waitlist();
    Booking book = new Booking();
    List res1;
    List res2;
    try{
        String f = "";
        String g = "";
        String name = StatusCustomerCombo.getSelectedItem().toString();
        res1 = wait.getPersonWaitlist(name);
        res2 = book.getPersonBooked(name);
        for(int i=0;i<res2.size();i++){
            
            if (i == 2){
                g+="\n";
                g +=res2.get(i).toString()+"   ";
            }else{
                
            g +=res2.get(i).toString()+"   ";
            
            }
        }
        
        for(int i=0;i<res1.size();i++){
            
            if (i == 2){
                f+="\n";
                f +=res1.get(i).toString()+"   ";
            }else{
                
            f +=res1.get(i).toString()+"   ";
            
            }
        }
            
        
       
    jTextArea3.setText("WAITLISTED:\n"+f);
    jTextArea2.setText("BOOKED:\n"+g);
    
    
    }
    
    catch(SQLException eq){
        eq.printStackTrace();}
    
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CancelNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelNameComboActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
    Flight flight = new Flight();
    Day day = new Day();
    Booking book = new Booking();
    Waitlist wait = new Waitlist();
    List Customers_d1;
    List Customers_d2;
    int result;
    int result1;
    int result2;
    int result6;
    int result7;
    List result11;
    int result12;
    List result13;
    int result14;
    String str="";
    String date1=day.getAllDays().get(0);
    String date2 =day.getAllDays().get(1);
    String name = DropFlightCombo.getSelectedItem().toString();// TODO add your handling code here:
    result = flight.deleteFlight(name);
    result11 = wait.shiftToBooking(name, Date.valueOf(date1));
    result13 = wait.shiftToBooking(name, Date.valueOf(date2));
    for (int i =0; i<result11.size();i++){
            result12 = wait.deleteWaitlist(result11.get(i).toString());
            str+= result11.get(i).toString();
        }
    
     for (int i =0; i<result13.size();i++){
            result14 = wait.deleteWaitlist(result11.get(i).toString());
            str+= result11.get(i).toString()+" ,";
        }
    jLabel36.setText(str+" deleted from waitlist for date:"+ date1);
       
    Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
    //result1 = book.deleteBookingDrop(name,Date.valueOf(date1));
    //result2 =  book.deleteBookingDrop(name,Date.valueOf(date1));
    try{
        
        Customers_d1 = book.getCustomersBooked(name,Date.valueOf(date1));
        //Customers_d2 = book.getCustomersBooked(name,Date.valueOf(date2));
        List cus = Flight.getAllFlights();
        
        //System.out.println(Customers_d2);
        result1 = book.deleteBookingDrop(name,Date.valueOf(date1));
        //result2 =  book.deleteBookingDrop(name,Date.valueOf(date2));
        int len1 = 0;
        int len2 = 0;
        int len3 = 0;
        int chc= 0;
        int chc2 = 0;
        //int x = book.getSeatsBooked(cus.get(0).toString(), Date.valueOf(date1));
        //int y = book.getSeatsBooked(cus.get(0).toString(), Date.valueOf(date2));
        //System.out.println(y);
        //System.out.println(x);
        
            
        while (len3 != Customers_d1.size()){
            int x = book.getSeatsBooked(cus.get(chc).toString(), Date.valueOf(date1));
            
            if (x != 2){
                result7 = book.addBooking( Customers_d1.get(len1).toString(), cus.get(chc).toString(), Date.valueOf(date1),timestamp );
                jLabel29.setText(Customers_d1.get(len1).toString()+" booked on flight: "+cus.get(chc).toString()+" departing: "+date1);
                
                //result1 = book.deleteBooking(name,Date.valueOf(date1));
                len1+=1;
                len3+=1;
            
                
                
            }else{
                
                
                len3+=1;
                chc+=1;
                jLabel34.setText(Customers_d1.get(chc).toString()+" cancelled as no alternate flight/seats left on date: "+date1);
                
                
            }
        }
    
        
    }
    catch(SQLException eq){
        
    }
    try{
        //Customers_d1 = book.getCustomersBooked(name,Date.valueOf(date1));
        Customers_d2 = book.getCustomersBooked(name,Date.valueOf(date2));
        List cus = Flight.getAllFlights();
        //System.out.println(Customers_d1);
       
        //result1 = book.deleteBookingDrop(name,Date.valueOf(date1));
        result2 =  book.deleteBookingDrop(name,Date.valueOf(date2));
        int len1 = 0;
        int len2 = 0;
        int chc= 0;
        int chc2 = 0;
        int len4 = 0;
        //int x = book.getSeatsBooked(cus.get(0).toString(), Date.valueOf(date1));
        //int y = book.getSeatsBooked(cus.get(0).toString(), Date.valueOf(date2));
        //System.out.println(y);
        //System.out.println(x);
        
            
        while (len4 != Customers_d2.size()){
           
            int y = book.getSeatsBooked(cus.get(chc2).toString(), Date.valueOf(date2));
            
            if (y != 2){
                result6 = book.addBooking( Customers_d2.get(chc2).toString(), cus.get(len2).toString(), Date.valueOf(date2),timestamp );
                jLabel30.setText(Customers_d2.get(chc2).toString()+" booked on flight: "+cus.get(chc).toString()+" departing: "+date2);
                //result1 = book.deleteBooking(name,Date.valueOf(date1));
                len2+=1;
                //chc2 +=1;
                len4+=1;
                
            }else{
                System.out.println("reached");
                //len2+=1;
                chc2+=1;
                len4+=1;
                try{
                jLabel36.setText(Customers_d2.get(chc2).toString()+" cancelled as no alternate flight/seats left on date: "+date2);}
                catch(Exception eq){
                    jLabel36.setText("No persons on the waitlist!");
                }
            }
        }
    }catch(SQLException eq){
        
    }
    BookingFNamCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
    FlightDayNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
    DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
    }//GEN-LAST:event_jButton5ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightSchedulerGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADDPASSENGERPANEL;
    private javax.swing.JButton AddBookingButton;
    private javax.swing.JButton AddFlightButton;
    private javax.swing.JTextField AddFlightNameTF;
    private javax.swing.JTextField AddFlightSeatsTF;
    private javax.swing.JPanel BOOKINGPANEL;
    private javax.swing.JComboBox<String> BookingDateCombo;
    private javax.swing.JComboBox<String> BookingFNamCombo;
    private javax.swing.JComboBox<String> BookingNameCombo;
    private javax.swing.JLabel BookingStatusLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> CancelDateCombo;
    private javax.swing.JComboBox<String> CancelNameCombo;
    private javax.swing.JComboBox<String> DropFlightCombo;
    private javax.swing.JComboBox<String> FlightDayDateCombo;
    private javax.swing.JComboBox<String> FlightDayNameCombo;
    private javax.swing.JButton FlightDayStatusButton;
    private javax.swing.JTextArea FlightDayTextArea;
    private javax.swing.JTabbedPane PAss;
    private javax.swing.JComboBox<String> StatusCustomerCombo;
    private javax.swing.JPanel WAITLISTPANEL;
    private javax.swing.JComboBox<String> WaitListCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
